# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: Introduce
    url: /about/
    weight: 20

  - name: Project
    url: /projects/

  - name: Study
    url: /study/
    weight: 40
    hasChildren: true
  - parent: Study
    name: 계획
    url: /interest/study1/
  - parent: Study
    name: 공부한 것
    url: /interest/study2/

  - name: Interest
    url: /interest/
    weight: 50
    haChildren: true
  - parent: Interest
    name: 유튜브
    url: /interest/inestest1/
  - parent: Interest
    name: IT, 뉴스레터
    url: /interest/inestest2/
